<?php
require_once "base/BEkuParamTransporteResponsableFlete.php";

class EkuParamTransporteResponsableFlete extends BEkuParamTransporteResponsableFlete {

    const RESPONSABLE_EMISOR_FACTURA_ELECTRONICA = 'EMISOR_FACTURA_ELECTRONICA';
    const RESPONSABLE_RECEPTOR_FACTURA_ELECTRONICA = 'RECEPTOR_FACTURA_ELECTRONICA';
    const RESPONSABLE_TERCERO = 'TERCERO';
    const RESPONSABLE_AGENTE_INTERMEDIARIO_TRANSPORTE = 'AGENTE_INTERMEDIARIO_TRANSPORTE';
    const RESPONSABLE_TRANSPORTE_PROPIO = 'TRANSPORTE_PROPIO';

}

?>