<?php
require_once "base/BEkuParamTipoMotivoEmisionRemito.php";

class EkuParamTipoMotivoEmisionRemito extends BEkuParamTipoMotivoEmisionRemito {

    const TIPO_TRASLADO_POR_VENTA = 'TRASLADO_POR_VENTA';
    const TIPO_TRASLADO_POR_CONSIGNACION = 'TRASLADO_POR_CONSIGNACION';
    const TIPO_EXPORTACION = 'EXPORTACION';
    const TIPO_TRASLADO_POR_COMPRA = 'TRASLADO_POR_COMPRA';
    const TIPO_IMPORTACION = 'IMPORTACION';
    const TIPO_TRASLADO_POR_DEVOLUCION = 'TRASLADO_POR_DEVOLUCION';
    const TIPO_TRASLADO_ENTRE_LOCALES_DE_LA_EMPRESA = 'TRASLADO_ENTRE_LOCALES_DE_LA_EMPRESA';
    const TIPO_TRASLADO_DE_BIENES_POR_TRANSFORMACION = 'TRASLADO_DE_BIENES_POR_TRANSFORMACION';
    const TIPO_TRASLADO_DE_BIENES_POR_REPARACION = 'TRASLADO_DE_BIENES_POR_REPARACION';
    const TIPO_TRASLADO_POR_EMISOR_MOVIL = 'TRASLADO_POR_EMISOR_MOVIL';
    const TIPO_EXHIBICION_O_DEMOSTRACION = 'EXHIBICION_O_DEMOSTRACION';
    const TIPO_PARTICIPACION_EN_FERIAS = 'PARTICIPACION_EN_FERIAS';
    const TIPO_TRASLADO_DE_ENCOMIENDA = 'TRASLADO_DE_ENCOMIENDA';
    const TIPO_DECOMISO = 'DECOMISO';
    const TIPO_OTRO = 'OTRO';

}

?>