<?php
require_once "base/BEkuParamTipoDe.php";

class EkuParamTipoDe extends BEkuParamTipoDe {

    const TIPO_FACTURA_ELECTRONICA = 'FACTURA_ELECTRONICA';
    const TIPO_FACTURA_ELECTRONICS_DE_EXPORTACION = 'FACTURA_ELECTRONICS_DE_EXPORTACION';
    const TIPO_FACTURA_ELECTRONICA_DE_IMPORTACION = 'FACTURA_ELECTRONICA_DE_IMPORTACION';
    const TIPO_AUTOFACTURA_ELECTRONICA = 'AUTOFACTURA_ELECTRONICA';
    const TIPO_NOTA_DE_CREDITO_ELECTRONICA = 'NOTA_DE_CREDITO_ELECTRONICA';
    const TIPO_NOTA_DE_DEBITO_ELECTRONICA = 'NOTA_DE_DEBITO_ELECTRONICA';
    const TIPO_NOTA_DE_REMISION_ELECTRONICA = 'NOTA_DE_REMISION_ELECTRONICA';
    const TIPO_COMPROBANTE_DE_RETENCION_ELECTRONICO = 'COMPROBANTE_DE_RETENCION_ELECTRONICO';

}

?>