<?php
require_once "base/BEkuParamResponsableEmisionRemito.php";

class EkuParamResponsableEmisionRemito extends BEkuParamResponsableEmisionRemito {

    const RESPONSABLE_EMISOR_DE_LA_FACTURA = 'EMISOR_DE_LA_FACTURA';
    const RESPONSABLE_POSEEDOR_DE_LA_FACTURA_Y_BIENES = 'POSEEDOR_DE_LA_FACTURA_Y_BIENES';
    const RESPONSABLE_EMPRESA_TRANSPORTISTA = 'EMPRESA_TRANSPORTISTA';
    const RESPONSABLE_DESPACHANTE_DE_ADUANAS = 'DESPACHANTE_DE_ADUANAS';
    const RESPONSABLE_AGENTE_DE_TRANSPORTE_O_INTERMEDIARIO = 'AGENTE_DE_TRANSPORTE_O_INTERMEDIARIO';

}

?>