<?php
require_once "base/BEkuParamTipoPago.php";

class EkuParamTipoPago extends BEkuParamTipoPago {

    const TIPO_EFECTIVO = 'EFECTIVO';
    const TIPO_CHEQUE = 'CHEQUE';
    const TIPO_TARJETA_DE_CREDITO = 'TARJETA_DE_CREDITO';
    const TIPO_TARJETA_DE_DEBITO = 'TARJETA_DE_DEBITO';
    const TIPO_TRANSFERENCIA = 'TRANSFERENCIA';
    const TIPO_GIRO = 'GIRO';
    const TIPO_BILLETERA_ELECTRONICA = 'BILLETERA_ELECTRONICA';
    const TIPO_TARJETA_EMPRESARIAL = 'TARJETA_EMPRESARIAL';
    const TIPO_VALE = 'VALE';
    const TIPO_RETENCION = 'RETENCION';
    const TIPO_PAGO_POR_ANTICIPO = 'PAGO_POR_ANTICIPO';
    const TIPO_VALOR_FISCAL = 'VALOR_FISCAL';
    const TIPO_VALOR_COMERCIAL = 'VALOR_COMERCIAL';
    const TIPO_COMPENSACION = 'COMPENSACION';
    const TIPO_PERMUTA = 'PERMUTA';
    const TIPO_PAGO_BANCARIO = 'PAGO_BANCARIO';
    const TIPO_PAGO_MOVIL = 'PAGO_MOVIL';
    const TIPO_DONACION = 'DONACION';
    const TIPO_PROMOCION = 'PROMOCION';
    const TIPO_CONSUMO_INTERNO = 'CONSUMO_INTERNO';
    const TIPO_PAGO_ELECTRONICO = 'PAGO_ELECTRONICO';
    const TIPO_OTRO = 'OTRO';

}

?>