<?php
require_once "base/BEkuParamTipoTransaccion.php";

class EkuParamTipoTransaccion extends BEkuParamTipoTransaccion {

    const TIPO_VENTA_DE_MERCADERIA = 'VENTA_DE_MERCADERIA';
    const TIPO_PRESTACION_DE_SERVICIOS = 'PRESTACION_DE_SERVICIOS';
    const TIPO_MIXTO_VENTA_DE_MERCADERIA_Y_SERVICIOS = 'MIXTO_VENTA_DE_MERCADERIA_Y_SERVICIOS';
    const TIPO_VENTA_DE_ACTIVO_FIJO = 'VENTA_DE_ACTIVO_FIJO';
    const TIPO_VENTA_DE_DIVISAS = 'VENTA_DE_DIVISAS';
    const TIPO_COMPRA_DE_DIVISAS = 'COMPRA_DE_DIVISAS';
    const TIPO_PROMOCION_O_ENTREGA_DE_MUESTRAS = 'PROMOCION_O_ENTREGA_DE_MUESTRAS';
    const TIPO_DONACION = 'DONACION';
    const TIPO_ANTICIPO = 'ANTICIPO';
    const TIPO_COMPRA_DE_PRODUCTOS = 'COMPRA_DE_PRODUCTOS';
    const TIPO_COMPRA_DE_SERVICIOS = 'COMPRA_DE_SERVICIOS';
    const TIPO_VENTA_DE_CREDITO_FISCAL = 'VENTA_DE_CREDITO_FISCAL';
    const TIPO_MUESTRAS_MEDICAS = 'MUESTRAS_MEDICAS';

}

?>