<?php 
require_once "base/BVtaAjusteHaberConcepto.php"; 
class VtaAjusteHaberConcepto extends BVtaAjusteHaberConcepto
{
    const TIPO_COBRO_FACTURA = 'COBRO_FACTURA';
    const TIPO_COBRO_ND = 'COBRO_ND';
    const TIPO_GASTOS_ADMINISTRATIVOS = 'GASTOS_ADMINISTRATIVOS';
    const TIPO_RETENCION_IIBB_MNES = 'RETENCION_IIBB_MNES';
    const TIPO_RETENCION_IIBB_BSAS = 'RETENCION_IIBB_BSAS';
    const TIPO_RETENCIONES_IVA = 'RETENCIONES_IVA';
    const TIPO_RETENCIONES_GANANCIAS = 'RETENCIONES_GANANCIAS';
    const TIPO_RETENCIONES_SUSS = 'RETENCIONES_SUSS';
    const TIPO_COMPENSACION = 'COMPENSACION';
}
?>