<?php
require_once "base/BVtaTipoPuntoVenta.php";

class VtaTipoPuntoVenta extends BVtaTipoPuntoVenta {

    const TIPO_FACTURA_ELECTRONICA = "FACTURA_ELECTRONICA";
    const TIPO_FACTURA_ELECTRONICA_EXPORTACION = "FACTURA_ELECTRONICA_EXPORTACION";
    const TIPO_FACTURA_ELECTRONICA_IMPORTACION = "FACTURA_ELECTRONICA_IMPORTACION";
    const TIPO_AUTOFACTURA_ELECTRONICA = "AUTOFACTURA_ELECTRONICA";
    const TIPO_NOTA_CREDITO_ELECTRONICA = "NOTA_CREDITO_ELECTRONICA";
    const TIPO_NOTA_DEBITO_ELECTRONICA = "NOTA_DEBITO_ELECTRONICA";
    const TIPO_NOTA_REMISION_ELECTRONICA = "NOTA_REMISION_ELECTRONICA";
    const TIPO_COMPROBANTE_RETENCION_ELECTRONICA = "COMPROBANTE_RETENCION_ELECTRONICA";
    const TIPO_RECIBO_DINERO = "RECIBO_DINERO";

}

?>